version: '3'

services:
  manager:
    container_name: manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
    environment:
      - debug=true
      - private_key=demo
      - use_threaded_image=true
      - thread_count=12
